name: '.NET Diagram Generator'
description: 'GitHub Action to generate UML class diagrams for .NET repositories.'
author: '@sator-imaging'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'share-2'
  color: 'purple'

inputs:
  output-dir:
    description: 'Relative output directory'
    default: 'UML'
  theme:
    description: 'PlantUML theme name'
    default: '_none_'

outputs:
  readme-path:
    description: 'Path to generated UML README'
    value: ${{ steps.set-output.outputs.readme }}
  html-path:
    description: 'Path to generated HTML diagram page'
    value: ${{ steps.set-output.outputs.html }}
  diff-path:
    description: 'Path to generated Markdown diff file'
    value: ${{ steps.set-output.outputs.diff }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # 6.0.2

    - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7  # v5.2.0
      with:
        dotnet-version: '8.x.x'  # For PlantUmlClassDiagramGenerator 

    - run: sudo apt-get update && sudo apt-get install -y plantuml graphviz
      shell: bash

    - run: dotnet tool install --global PlantUmlClassDiagramGenerator --version 1.4.0
      shell: bash

    - name: Generate UML
      id: generate
      shell: bash
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        bash $GITHUB_ACTION_PATH/entrypoint.sh \
          "${{ inputs.output-dir }}" \
          "${{ inputs.theme }}"

    - name: Set output
      id: set-output
      shell: bash
      run: |
        echo "readme=${{ inputs.output-dir }}/README.md" >> $GITHUB_OUTPUT
        echo "html=${{ inputs.output-dir }}/index.html" >> $GITHUB_OUTPUT
        echo "diff=${{ inputs.output-dir }}/DIFF.md" >> $GITHUB_OUTPUT
