#!/bin/bash
set -e

projects_glob="${1:-**/*.csproj}"
output_folder="${2:-UML}"
fallback="${3:-true}"

mkdir -p "$output_folder"

csproj_list=$(find . -name "$(basename "$projects_glob")")

generated_any=false

generate_diagram() {
    local source_dir="$1"
    local diagram_name="$2"
    local uml_file="$output_folder/$diagram_name.uml"
    local generated_puml="$output_folder/$diagram_name.puml"

    puml-gen "$source_dir" "$generated_puml" \
      -createAssociation -excludePaths bin,obj,Properties -public \
      || echo "⚠ uml generation failed: $diagram_name"

    if [ -f "$generated_puml" ]; then
        mv "$generated_puml" "$uml_file"
        plantuml -tsvg "$uml_file" || echo "⚠ svg generation failed: $diagram_name"
        generated_any=true
    fi
}

# =========================
# Generate UML for csproj
# =========================
if [ -n "$csproj_list" ]; then
    for csproj in $csproj_list; do
        proj_name=$(basename "$csproj" .csproj)
        proj_dir=$(dirname "$csproj")

        echo "→ Processing project: $proj_name"

        dotnet restore "$csproj" || echo "⚠ restore failed: $proj_name"
        generate_diagram "$proj_dir" "$proj_name"
    done
fi

# =========================
# Fallback to .cs files
# =========================
if [ "$generated_any" = false ] && [ "$fallback" = "true" ]; then
    echo "⚠ No csproj → fallback to .cs"

    cs_dirs=$(
        find . -type f -name "*.cs" -printf '%h\n' | sort -u | while IFS= read -r dir; do
            parent="$dir"
            keep=true

            while [ "$parent" != "." ] && [ "$parent" != "/" ]; do
                parent=$(dirname "$parent")
                if find "$parent" -maxdepth 1 -type f -name "*.cs" | grep -q .; then
                    keep=false
                    break
                fi
            done

            if [ "$keep" = true ]; then
                echo "$dir"
            fi
        done
    )

    if [ -n "$cs_dirs" ]; then
        while IFS= read -r cs_dir; do
            [ -n "$cs_dir" ] || continue

            dir_name=$(basename "$cs_dir")

            echo "→ Processing directory: $dir_name"

            generate_diagram "$cs_dir" "$dir_name"
        done <<EOF
$cs_dirs
EOF
    fi
fi

# =========================
# Generate README
# =========================
README="$output_folder/README.md"

echo "# Overall Changes" > "$README"
echo "Generated by [dotnet-diagram](https://github.com/sator-imaging/dotnet-diagram) @ $(date +'%Y-%m-%d %H:%M:%S')" >> "$README"
echo "" >> "$README"

git fetch origin main || true

full_diff=$(git diff origin/main -- "$output_folder"/*.uml || true)

if [ -z "$full_diff" ]; then
    echo "_No changes_" >> "$README"
else
    echo '```diff' >> "$README"
    echo "$full_diff" >> "$README"
    echo '```' >> "$README"
fi

echo "" >> "$README"

# =========================
# Embed csproj diagrams
# =========================
found_any=false

for svg in "$output_folder"/*.svg; do
    [ -f "$svg" ] || continue

    found_any=true
    name=$(basename "$svg" .svg)
    uml_file="$output_folder/$name.uml"

    echo "# $name" >> "$README"
    echo "" >> "$README"

    echo "![${name}](${name}.svg)" >> "$README"
    echo "" >> "$README"
    echo "<details>" >> "$README"
    echo "<summary>PlantUML</summary>" >> "$README"
    echo "" >> "$README"
    echo '```plantuml' >> "$README"
    cat "$uml_file" >> "$README"
    echo '```' >> "$README"
    echo "</details>" >> "$README"
    echo "" >> "$README"

    file_diff=$(git diff origin/main -- "$uml_file" || true)

    if [ -n "$file_diff" ]; then
        echo '```diff' >> "$README"
        echo "$file_diff" >> "$README"
        echo '```' >> "$README"
        echo "" >> "$README"
    fi
done

# =========================
# Fallback for nothing
# =========================
if [ "$found_any" = false ]; then
    echo "_No UML diagrams generated_" >> "$README"
fi

echo "✔ UML generation completed (non-blocking)"
