#!/bin/bash
set -e

output_folder="${1:-UML}"
theme="${2:-mars}"

mkdir -p "$output_folder"

csproj_list=$(find . -name "*.csproj")

generated_any=false

generate_diagram() {
    local source_dir="$1"
    local diagram_name="$2"
    local uml_file="$output_folder/$diagram_name.uml"
    local temp_dir

    temp_dir=$(mktemp -d /tmp/dotnet-diagram.XXXXXX)

    puml-gen "$source_dir" "$temp_dir" -dir -allInOne \
      -createAssociation -excludePaths bin,obj,Properties -public \
      || echo "⚠ uml generation failed: $diagram_name"

    if [ -f "$temp_dir/include.puml" ]; then
        mv "$temp_dir/include.puml" "$uml_file"
        plantuml --theme "$theme" -tsvg "$uml_file" || echo "⚠ svg generation failed: $diagram_name"
        generated_any=true
    fi

    rm -rf "$temp_dir"
}

# =========================
# Generate UML for csproj
# =========================
if [ -n "$csproj_list" ]; then
    for csproj in $csproj_list; do
        proj_name=$(basename "$csproj" .csproj)
        proj_dir=$(dirname "$csproj")

        echo "→ Processing project: $proj_name"

        dotnet restore "$csproj" || echo "⚠ restore failed: $proj_name"
        generate_diagram "$proj_dir" "$proj_name"
    done
fi

# =========================
# Fallback to .cs files
# =========================
if [ "$generated_any" = false ]; then
    echo "⚠ No csproj → fallback to .cs"

    cs_dirs=$(
        find . -type f -name "*.cs" -printf '%h\n' | sort -u | while IFS= read -r dir; do
            parent="$dir"
            keep=true

            while [ "$parent" != "." ] && [ "$parent" != "/" ]; do
                parent=$(dirname "$parent")
                if find "$parent" -maxdepth 1 -type f -name "*.cs" | grep -q .; then
                    keep=false
                    break
                fi
            done

            if [ "$keep" = true ]; then
                echo "$dir"
            fi
        done
    )

    if [ -n "$cs_dirs" ]; then
        while IFS= read -r cs_dir; do
            [ -n "$cs_dir" ] || continue

            dir_name=$(basename "$cs_dir")

            echo "→ Processing directory: $dir_name"

            generate_diagram "$cs_dir" "$dir_name"
        done <<EOF
$cs_dirs
EOF
    fi
fi

# =========================
# Generate Outputs
# =========================
README="$output_folder/README.md"
INDEX_HTML="$output_folder/index.html"
DIFF_MD="$output_folder/DIFF.md"
GENERATED_AT="$(date +'%Y-%m-%d %H:%M:%S')"

echo "Generated by [dotnet-diagram](https://github.com/sator-imaging/dotnet-diagram) @ ${GENERATED_AT}" > "$README"
echo "" >> "$README"

echo "Generated by [dotnet-diagram](https://github.com/sator-imaging/dotnet-diagram) @ ${GENERATED_AT}" > "$DIFF_MD"
echo "" >> "$DIFF_MD"

cat > "$INDEX_HTML" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>dotnet-diagram</title>
  <style>
    body { font-family: sans-serif; line-height: 1.5; margin: 2rem; }
    img { width: 100%; max-width: 100%; height: auto; display: block; }
    pre { overflow: auto; padding: 1rem; background: #f6f8fa; }
    section { margin: 2rem 0; }
  </style>
</head>
<body>
  <p>Generated by <a href="https://github.com/sator-imaging/dotnet-diagram">dotnet-diagram</a> @ ${GENERATED_AT}</p>
EOF

git fetch origin main || true

found_any=false

uml_diff=$(git diff origin/main -- "$output_folder"/*.uml || true)
if [ -n "$uml_diff" ]; then
    found_any=true
    echo '```diff' >> "$DIFF_MD"
    echo "$uml_diff" >> "$DIFF_MD"
    echo '```' >> "$DIFF_MD"
    echo "" >> "$DIFF_MD"
fi

echo "" >> "$DIFF_MD"
echo "" >> "$INDEX_HTML"

# =========================
# Embed csproj diagrams
# =========================
for svg in "$output_folder"/*.svg; do
    [ -f "$svg" ] || continue

    name=$(basename "$svg" .svg)
    uml_file="$output_folder/$name.uml"

    echo "# $name" >> "$README"
    echo "" >> "$README"

    echo "![${name}](${name}.svg)" >> "$README"
    echo "" >> "$README"
    echo "<details>" >> "$README"
    echo "<summary>PlantUML</summary>" >> "$README"
    echo "" >> "$README"
    echo '```plantuml' >> "$README"
    cat "$uml_file" >> "$README"
    echo '```' >> "$README"
    echo "</details>" >> "$README"
    echo "" >> "$README"

    svg_base64=$(base64 "$svg" | tr -d '\n')
    echo "  <section>" >> "$INDEX_HTML"
    echo "    <h1>${name}</h1>" >> "$INDEX_HTML"
    echo "    <img alt=\"${name}\" src=\"data:image/svg+xml;base64,${svg_base64}\">" >> "$INDEX_HTML"
    echo "    <details>" >> "$INDEX_HTML"
    echo "      <summary>PlantUML</summary>" >> "$INDEX_HTML"
    echo "      <pre><code>$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$uml_file")</code></pre>" >> "$INDEX_HTML"
    echo "    </details>" >> "$INDEX_HTML"
    echo "  </section>" >> "$INDEX_HTML"

    file_diff=$(git diff origin/main -- "$uml_file" || true)

    if [ -n "$file_diff" ]; then
        found_any=true
        echo "# $name" >> "$DIFF_MD"
        echo "" >> "$DIFF_MD"
        echo "<details>" >> "$DIFF_MD"
        echo "<summary>Diff</summary>" >> "$DIFF_MD"
        echo "" >> "$DIFF_MD"
        echo '```diff' >> "$DIFF_MD"
        echo "$file_diff" >> "$DIFF_MD"
        echo '```' >> "$DIFF_MD"
        echo "</details>" >> "$DIFF_MD"
        echo "" >> "$DIFF_MD"

        echo "    <details>" >> "$INDEX_HTML"
        echo "      <summary>Diff</summary>" >> "$INDEX_HTML"
        echo "      <pre><code>$(printf '%s' "$file_diff" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')</code></pre>" >> "$INDEX_HTML"
        echo "    </details>" >> "$INDEX_HTML"
    fi
done

# =========================
# Fallback for nothing
# =========================
if [ "$found_any" = false ]; then
    echo "_No changes_" >> "$DIFF_MD"
fi

echo "</body>" >> "$INDEX_HTML"
echo "</html>" >> "$INDEX_HTML"

echo "✔ Generation completed"
