name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Permissions required for creating PR
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
      
      - id: diagram
        uses: ./


      - name: Step Summary
        run: cat "${{ steps.diagram.outputs.diff-path }}" >> $GITHUB_STEP_SUMMARY

      - name: Debug SVG
        run: |
          if [ -f UML/Tests.svg ]; then
            echo '```svg' >> $GITHUB_STEP_SUMMARY
            cat UML/Tests.svg >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v7
        with:
          name: dotnet-diagram-html
          path: UML/index.html
          archive: false
          if-no-files-found: error


      - name: Create PR
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          BRANCH="auto/diagram-update-$TIMESTAMP"

          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          git checkout -b $BRANCH
          git add .
          git commit -m "[bot] ${{ github.workflow }} ($(date +'%Y-%m-%d %H:%M:%S'))" \
            || exit 0
          git push origin $BRANCH

          gh pr create \
            --fill-verbose \
            --base main \
            --head $BRANCH
